# -*- coding: UTF-8 -*-
# generated by lino.sphinxcontrib.help_text_builder
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
help_texts = {
    'lino_riche.lib.clocking.models.ServiceReport' : _("""A service report is a document used in various discussions with
a stakeholder."""),
    'lino_riche.lib.clocking.models.ServiceReport.user' : _("""This can be empty and will then show the working time of all
users."""),
    'lino_riche.lib.riche.migrate.Migrator' : _("""The standard migrator for riche."""),
    'lino_riche.lib.riche.user_types.EndUser' : _("""An end user is somebody who uses our software and may report
tickets, but won't work on them."""),
    'lino_riche.lib.riche.user_types.Consultant' : _("""A consultant is somebody who may both report tickets and work
on them."""),
    'lino_riche.lib.riche.user_types.Developer' : _("""A developer is somebody who may both report tickets and work
on them."""),
    'lino_riche.lib.riche.user_types.Senior' : _("""A senior developer is a developer who is additionally
responsible for triaging tickets"""),
    'lino_riche.lib.riche.user_types.SiteAdmin' : _("""Can do everything."""),
    'lino_riche.lib.tickets.Plugin' : _("""Adds the lino_xl.lib.votes plugin."""),
    'lino_riche.lib.tickets.models.TicketDetail' : _("""Customized detail_lyout for Tickets.  Replaces waiting_for by
faculties"""),
    'lino_riche.lib.users.desktop.UserDetail' : _("""Layout of User Detail in Lino riche."""),
}
